/* Generated by AN DISI Unibo */ 
package it.unibo.maxstaytime

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Maxstaytime ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Table = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("MAXSTAYTIME | Start")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("MAXSTAYTIME | Wait")
						updateResourceRep( "maxstaytime_wait"  
						)
					}
					 transition(edgeName="t037",targetState="newTimer",cond=whenDispatch("startTimer"))
					transition(edgeName="t038",targetState="resume",cond=whenDispatch("resumeTimer"))
					transition(edgeName="t039",targetState="stop",cond=whenDispatch("stopTimer"))
					transition(edgeName="t040",targetState="timerExpired",cond=whenDispatch("maxStayTimerExpired"))
					transition(edgeName="t041",targetState="endWork",cond=whenDispatch("end"))
				}	 
				state("newTimer") { //this:State
					action { //it:State
						println("MAXSTAYTIME | newTimer")
						if( checkMsgContent( Term.createTerm("startTimer(TABLE)"), Term.createTerm("startTimer(TABLE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0).toInt() == 1  
								 ){forward("startTimer", "startTimer(1)" ,"maxstaytimetable1" ) 
								}
								if(  payloadArg(0).toInt() == 2  
								 ){forward("startTimer", "startTimer(2)" ,"maxstaytimetable2" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("resume") { //this:State
					action { //it:State
						println("MAXSTAYTIME | resume")
						if( checkMsgContent( Term.createTerm("resumeTimer(TABLE)"), Term.createTerm("resumeTimer(TABLE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0).toInt() == 1  
								 ){forward("resumeTimer", "resumeTimer(1)" ,"maxstaytimetable1" ) 
								}
								if(  payloadArg(0).toInt() == 2  
								 ){forward("resumeTimer", "resumeTimer(2)" ,"maxstaytimetable2" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("stop") { //this:State
					action { //it:State
						println("MAXSTAYTIME | stop")
						if( checkMsgContent( Term.createTerm("stopTimer(TABLE)"), Term.createTerm("stopTimer(TABLE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0).toInt() == 1  
								 ){forward("stopTimer", "stopTimer(1)" ,"maxstaytimetable1" ) 
								}
								if(  payloadArg(0).toInt() == 2  
								 ){forward("stopTimer", "stopTimer(2)" ,"maxstaytimetable2" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("timerExpired") { //this:State
					action { //it:State
						println("MAXSTAYTIME | timerExpired")
						if( checkMsgContent( Term.createTerm("maxStayTimerExpired(TABLE)"), Term.createTerm("maxStayTimerExpired(TABLE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Table = payloadArg(0).toInt()
								forward("maxStayTimerExpired", "maxStayTimerExpired($Table)" ,"waitermind" ) 
						}
						updateResourceRep( "maxstaytime_timerExpired"  
						)
						 readLine()  
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("endWork") { //this:State
					action { //it:State
						println("MAXSTAYTIME | End work")
						terminate(0)
					}
				}	 
			}
		}
}
