/* Generated by AN DISI Unibo */ 
package it.unibo.smartbell

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartbell ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val Temp_max = 37.5
				var Client_temp = 36.0
				var Id_client = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("SMARTBELL | Start")
						updateResourceRep( "s0 smartbell"  
						)
					}
					 transition( edgeName="goto",targetState="waitRing", cond=doswitch() )
				}	 
				state("waitRing") { //this:State
					action { //it:State
						println("SMARTBELL | Wait ring")
						updateResourceRep( "waitRing"  
						)
					}
					 transition(edgeName="t08",targetState="checkTempClient",cond=whenRequest("enter_request_client"))
					transition(edgeName="t09",targetState="endWork",cond=whenDispatch("end"))
				}	 
				state("checkTempClient") { //this:State
					action { //it:State
						println("SMARTBELL | Check temp client")
						updateResourceRep( "checkTempClient"  
						)
						if( checkMsgContent( Term.createTerm("enter_request_client(TEMP)"), Term.createTerm("enter_request_client(TEMP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("SMARTBELL | Entry request from CLIENT with ID: $Id_client and TEMP: ${payloadArg(0)}")
								 Client_temp = payloadArg(0).toDouble()  
						}
						if(  Client_temp < Temp_max  
						 ){println("SMARTBELL | The client can enter - Temp Ok")
						request("smartbell_enter_request", "smartbell_enter_request($Id_client)" ,"waiter" )  
						}
						else
						 {println("SMARTBELL | The client can't enter - Temp Ko")
						 answer("enter_request_client", "enter_reply_from_smartbell_n", "enter_reply_from_smartbell_n($Id_client)"   )  
						 forward("go_to_wait_ring", "go_to_wait_ring(PAYLOAD)" ,"smartbell" ) 
						 }
					}
					 transition(edgeName="t110",targetState="clientEnter",cond=whenReply("client_accept"))
					transition(edgeName="t111",targetState="clientEnterWithTime",cond=whenReply("client_accept_with_time"))
					transition(edgeName="t112",targetState="waitRing",cond=whenDispatch("go_to_wait_ring"))
				}	 
				state("clientEnterWithTime") { //this:State
					action { //it:State
						println("SMARTBELL | The client must wait time")
						updateResourceRep( "clientEnterWithTime"  
						)
						if( checkMsgContent( Term.createTerm("client_accept_with_time(MAXSTAYTIME)"), Term.createTerm("client_accept_with_time(MAXSTAYTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("enter_request_client", "enter_reply_from_smartbell_with_time", "enter_reply_from_smartbell_with_time($Id_client,${payloadArg(0)})"   )  
						}
						 Id_client++  
					}
					 transition( edgeName="goto",targetState="waitRing", cond=doswitch() )
				}	 
				state("clientEnter") { //this:State
					action { //it:State
						println("SMARTBELL | The client can enter")
						updateResourceRep( "clientEnter"  
						)
						if( checkMsgContent( Term.createTerm("client_accept(TABLE)"), Term.createTerm("client_accept(TABLE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("enter_request_client", "enter_reply_from_smartbell", "enter_reply_from_smartbell($Id_client,${payloadArg(0)})"   )  
						}
					}
					 transition( edgeName="goto",targetState="waitRing", cond=doswitch() )
				}	 
				state("endWork") { //this:State
					action { //it:State
						println("SMARTBELL | End work")
						updateResourceRep( "endWork"  
						)
						terminate(0)
					}
				}	 
			}
		}
}
