/* Generated by AN DISI Unibo */ 
package it.unibo.smartbell

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartbell ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val TempMax = 37.5
				var ClientTemp = 36.0
				var ID_client = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("SMARTBELL | Start")
					}
					 transition( edgeName="goto",targetState="waitRing", cond=doswitch() )
				}	 
				state("waitRing") { //this:State
					action { //it:State
						println("SMARTBELL | waitRing")
					}
					 transition(edgeName="t054",targetState="checkTempClient",cond=whenRequest("enterRequestClient"))
					transition(edgeName="t055",targetState="endWork",cond=whenDispatch("end"))
				}	 
				state("checkTempClient") { //this:State
					action { //it:State
						println("SMARTBELL | checkTempClient")
						if( checkMsgContent( Term.createTerm("enterRequestClient(TEMP)"), Term.createTerm("enterRequestClient(TEMP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("SMARTBELL | Entry request from CLIENT with ID: $ID_client and TEMP: ${payloadArg(0)}")
								
												ClientTemp = payloadArg(0).toDouble()
						}
						if(  ClientTemp < TempMax  
						 ){println("SMARTBELL | The client can enter - Temperature OK")
						request("smartbellEnterRequest", "smartbellEnterRequest($ID_client)" ,"waitermind" )  
						}
						else
						 {println("SMARTBELL | The client can't enter - Temperature KO")
						 updateResourceRep( "{\"ID\":" + "\"" + ID_client.toString() + "\"," + "\"State\":" + "\"" + "checkTempClient" + "\"," + "\"Temp\":" + "\"" + ClientTemp.toString() + "\"" + "}"  
						 )
						 answer("enterRequestClient", "enterReplyFromSmartbellNeg", "enterReplyFromSmartbellNeg($ID_client)"   )  
						 forward("goToWaitRing", "goToWaitRing(PAYLOAD)" ,"smartbell" ) 
						 
						 				ID_client++
						 }
					}
					 transition(edgeName="t156",targetState="clientEnter",cond=whenReply("clientAccept"))
					transition(edgeName="t157",targetState="clientEnterWithTime",cond=whenReply("clientAcceptWithTime"))
					transition(edgeName="t158",targetState="waitRing",cond=whenDispatch("goToWaitRing"))
				}	 
				state("clientEnter") { //this:State
					action { //it:State
						println("SMARTBELL | clientEnter")
						if( checkMsgContent( Term.createTerm("clientAccept(ID)"), Term.createTerm("clientAccept(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "{\"ID\":" + "\"" + payloadArg(0).toString() + "\"," + "\"State\":" + "\"" + "clientEnter" + "\"" + "}"  
								)
								answer("enterRequestClient", "enterReplyFromSmartbell", "enterReplyFromSmartbell(${payloadArg(0)})"   )  
						}
						
									ID_client++
					}
					 transition( edgeName="goto",targetState="waitRing", cond=doswitch() )
				}	 
				state("clientEnterWithTime") { //this:State
					action { //it:State
						println("SMARTBELL | clientEnterWithTime")
						if( checkMsgContent( Term.createTerm("clientAcceptWithTime(ID,MAXSTAYTIME)"), Term.createTerm("clientAcceptWithTime(ID,MAXWAITINGTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("SMARTBELL | Inform the client about the total maximum waiting time: ${payloadArg(1)} milliseconds")
								updateResourceRep( "{\"ID\":" + "\"" + payloadArg(0).toString() + "\"," + "\"State\":" + "\"" + "clientEnterWithTime" + "\"," + "\"MWT\":" + "\"" + payloadArg(1).toString() + "\"" + "}"  
								)
								answer("enterRequestClient", "enterReplyFromSmartbellWithTime", "enterReplyFromSmartbellWithTime($ID_client,${payloadArg(0)})"   )  
						}
						
									ID_client++
					}
					 transition( edgeName="goto",targetState="waitRing", cond=doswitch() )
				}	 
				state("endWork") { //this:State
					action { //it:State
						println("SMARTBELL | End work")
						terminate(0)
					}
				}	 
			}
		}
}
