/* Generated by AN DISI Unibo */ 
package it.unibo.maxstaytimetable1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Maxstaytimetable1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val TimeMaxStay 	= 100000L
				var StartTime 		= 0L
				var TimerDone 		= 0L
				var TimerGlobalDone = 0L
				var TimeAfterResume = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("MAXSTAYTIMETABLE1 | Start")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("MAXSTAYTIMETABLE1 | Wait")
					}
					 transition(edgeName="t041",targetState="newTimer",cond=whenDispatch("startTimer"))
					transition(edgeName="t042",targetState="wait",cond=whenDispatch("stopTimer"))
					transition(edgeName="t043",targetState="resume",cond=whenDispatch("resumeTimer"))
				}	 
				state("newTimer") { //this:State
					action { //it:State
						println("MAXSTAYTIMETABLE1 | newTimer")
						StartTime = getCurrentTime()
						
									TimerGlobalDone = 0
						stateTimer = TimerActor("timer_newTimer", 
							scope, context!!, "local_tout_maxstaytimetable1_newTimer", TimeMaxStay )
					}
					 transition(edgeName="t144",targetState="timerExpired",cond=whenTimeout("local_tout_maxstaytimetable1_newTimer"))   
					transition(edgeName="t145",targetState="stop",cond=whenDispatch("stopTimer"))
				}	 
				state("stop") { //this:State
					action { //it:State
						println("MAXSTAYTIMETABLE1 | stop")
						TimerDone = getDuration(StartTime)
						
									TimerGlobalDone += TimerDone
					}
					 transition(edgeName="t246",targetState="resume",cond=whenDispatch("resumeTimer"))
				}	 
				state("resume") { //this:State
					action { //it:State
						println("MAXSTAYTIMETABLE1 | resume")
						
									TimeAfterResume = TimeMaxStay - TimerGlobalDone
						StartTime = getCurrentTime()
						stateTimer = TimerActor("timer_resume", 
							scope, context!!, "local_tout_maxstaytimetable1_resume", TimeAfterResume )
					}
					 transition(edgeName="t347",targetState="timerExpired",cond=whenTimeout("local_tout_maxstaytimetable1_resume"))   
					transition(edgeName="t348",targetState="stop",cond=whenDispatch("stopTimer"))
				}	 
				state("timerExpired") { //this:State
					action { //it:State
						println("MAXSTAYTIMETABLE1 | timerExpired")
						forward("maxStayTimerExpired", "maxStayTimerExpired(1)" ,"maxstaytime" ) 
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
